# Usando a imagem base do Node.js
FROM node:16-alpine

# Definindo o diretório de trabalho no container
WORKDIR /app

# Criando package.json e instalando dependências
RUN npm init -y
RUN npm install express --save

# Copiando o arquivo server.js para o container
COPY server.js .

# Expondo a porta 3000
EXPOSE 3000

# Comando para rodar o servidor
CMD ["node", "server.js"]
